### ISSUE TITLE
document renaming does not work with site routing store

### ISSUE THREAD

**Issue by ArnoLP** [Acosix/alfresco-simple-content-stores#11]
Hello,
I just tested the last version with Alfresco community 5.2 (GA 201707).

I use it with the site routing store "context".

I got one problem with document renaming : if the parameter "moveStoresOnNodeMoveOrCopy" is set to true, then I get an error when I try to rename a document in a "site content store" (not if the document is in the "original" contentstore). If this parameter is set to false, then the renaming works.

Error screenshot : 

![pb_sitecontentstore](https://user-images.githubusercontent.com/21683549/35813312-9213c67a-0a93-11e8-8181-4b651f348048.jpg)

Can you help, please ?

Thanks in advance.

My configuration is the following : 

```
# enable the addon
simpleContentStores.enabled=true

# define the names of stores to configure
# (multiple stores can be listed in comma-separated fashion)
simpleContentStores.customStores=newSiteFileStore,siteRoutingStore
# use the store as the global standard (instead of default fileContentStore)
simpleContentStores.rootStore=siteRoutingStore

# define siteRoutingStore as a routing store
simpleContentStores.customStore.siteRoutingStore.type=siteRoutingStore
# store all non-routed content into the default file content store
simpleContentStores.customStore.siteRoutingStore.ref.fallbackStore=fileContentStore
simpleContentStores.customStore.siteRoutingStore.value.moveStoresOnNodeMoveOrCopy=true


simpleContentStores.customStore.siteRoutingStore.map.storeBySitePreset.ref.site-dashboard=newSiteFileStore

simpleContentStores.customStore.siteRoutingStore.map.storeBySite.ref.essai2=fileContentStore


simpleContentStores.customStore.newSiteFileStore.type=siteRoutingFileStore
simpleContentStores.customStore.newSiteFileStore.value.protocol=site-store
simpleContentStores.customStore.newSiteFileStore.value.rootDirectory=${dir.root}/sitecontentstore
simpleContentStores.customStore.newSiteFileStore.value.useSiteFolderInGenericDirectories=true

```

**Comment by AFaust** [comment]
Can you provide a stacktrace for that error? It would be nice to know at what code line that error is being triggered.

**Comment by ArnoLP** [comment]
Hello,

sorry for the delay for my feedback.

I just retested this case, and I don't get any trace in the logs. I only get the error displayed in the Share user interface, but nothing is traced in the logs.

**Comment by AFaust** [comment]
Finally I had some time to reproduce and fix this issue. The move handling did not distinguish between a move and a rename, as well as between move in site / between sites. This has been fixed now.
