### ISSUE TITLE
"Encrypting Store" wiki page : command to create the master key store

### ISSUE THREAD

**Issue by rouxemmanuel** [Acosix/alfresco-simple-content-stores#17]
Hi Axel,

This is not an issue but an update of your wiki :
In "Encrypting Store" wiki page, command to create the master key store for your configuration example is :
JAVA_HOME/bin/keytool -genkey -alias encrypt -keyalg RSA -keypass encrypt -storepass encrypt -keystore [ALFRESCO_INSTALL_DIR]/shared/classes/classes/keystore.jks

Regards,
Emmanuel

**Comment by AFaust** [comment]
Now documented in the relevant [store documentation](https://github.com/Acosix/alfresco-simple-content-stores/blob/master/docs/EncryptingStore.md#preparing-the-master-key) (will no longer use wiki for documentation, but use Markdown documents in source tree, which are easier to keep track off for different versions of the addon).
