### ISSUE TITLE
Build Failure.

### ISSUE THREAD

**Issue by monicakumari** [Acosix/alfresco-simple-content-stores#28]
Hi.. I am not  able to build amp. Its showing me below error : 

> [INFO] Scanning for projects...
[INFO] 
[INFO] --< de.acosix.alfresco.simplecontentstores:de.acosix.alfresco.simplecontentstores.repo >--
[INFO] Building Acosix Alfresco Simple Content Stores - Repository Module 1.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ de.acosix.alfresco.simplecontentstores.repo ---
[INFO] Deleting /home/monica/Documents/test-projects/alfresco-simple-content-stores/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ de.acosix.alfresco.simplecontentstores.repo ---
[INFO] Skipping Rule Enforcement.
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (Enforce Requirements) @ de.acosix.alfresco.simplecontentstores.repo ---
[INFO] Skipping Rule Enforcement.
[INFO] 
[INFO] --- maven-toolchains-plugin:3.0.0:toolchain (default) @ de.acosix.alfresco.simplecontentstores.repo ---
[INFO] Required toolchain: jdk [ version='1.8' ]
[ERROR] No toolchain found for type jdk
[ERROR] Cannot find matching toolchain definitions for the following toolchain types:
jdk [ version='1.8' ]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.818 s
[INFO] Finished at: 2020-05-21T17:07:19+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-toolchains-plugin:3.0.0:toolchain (default) on project de.acosix.alfresco.simplecontentstores.repo: Cannot find matching toolchain definitions for the following toolchain types:
[ERROR] jdk [ version='1.8' ]
[ERROR] Please make sure you define the required toolchains in your ~/.m2/toolchains.xml file.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Please guide.

Thanks.

**Comment by AFaust** [comment]
The requirement to have Toolchains set up to access a JDK 8 installation is [documented here](https://github.com/Acosix/alfresco-simple-content-stores#maven-toolchains) - please check if you have done so.

**Comment by monicakumari** [comment]
Thank you. there was some configuration issue with toolchains.xml file. that helped.

I have another issue, I am trying to encrypt contentstore. I have created keystore.jks file using below command :
 `keytool -genkey -alias myRsaKey -keyalg RSA -keystore /home/keystore.jks -keysize 2048`

and updated property in alfresco-global.properties file : simpleContentStores.customStore.myEncryptingStore.value.keyStorePath=classpath:/home/keystore.jks

but on restarting instance its throwing errors ,one line from them is :

> Caused by: java.io.FileNotFoundException: class path resource [/home/keystore.jks] cannot be resolved to absolute file path because it does not reside in the file system

Please guide, what should be the path for keystore.jks file or Is there any permission issue or something ?

Thanks.

**Comment by AFaust** [comment]
You cannot use the classpath: prefix in this case, which is an entry point into a virtual file system defined by the Java class loader and only indirectly resolves to files on the file system. You have to use the file: prefix

**Comment by monicakumari** [comment]
Thanks a lot. It worked.. 

I am sorry, One last question I wanted to know,
Will it work with s3? I mean if the contentstore is in s3 bukced and instance is connected with s3-adaptor (https://github.com/Redpill-Linpro/alfresco-s3-adapter) , will this encryting contentstore work ?

Thanks.

**Comment by AFaust** [comment]
Unless other addons or I take specific steps to implement a compatibility layer and configuration support for the properites-based configuration, any content stores or adapters that they provide will not immediately work with this addon. I have not yet investigated what would be necessary to support the specific addon you linked, but have general plans to add S3 / Azure support to my addon sometime in the future.

**Comment by monicakumari** [comment]
Okay great. Thanks a lot for your help.
