### ISSUE TITLE
Installation Error: the amp will overwrite xz-1.8.jar

### ISSUE THREAD

**Issue by maoamid** [Acosix/alfresco-simple-content-stores#33]
Hi,
I need some assistance please with the following installation error:

`03020001 An error was encountered during deployment of the AMP into the WAR: 03020000 ERROR: The amp will overwrite an existing file in the war '/WEB-INF/lib/xz-1.8.jar'. Execution halted.  By specifying -force , you can force installation of AMP regardless of the current war state.`

Centos 7.9 ( clean installation of Alfresco 6.2 community edition using distribution files )
```
mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 1.8.0_282, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.15.2.el7.x86_64", arch: "amd64", family: "unix"
```

file used:
de.acosix.alfresco.simplecontentstores.repo-1.1.1-SNAPSHOT.amp
de.acosix.alfresco.utility.core.repo-1.2.6-SNAPSHOT.amp
de.acosix.alfresco.utility.core.share-1.2.6-SNAPSHOT.amp

**Comment by AFaust** [comment]
Alfresco 6.2 already ships the xz library, which previous versions did not. Therefor the "conflict" exists, but can safely be dealt with using the `force` flag.

**Comment by AFaust** [comment]
With the new development cycle for version 1.2, the XZ library will no longer be included in the AMP. If any users of this project want to use it on Alfresco 5.2, they need to install the library manually - all newer versions already bundle it, and this project will no longer support versions prior to Alfresco 5.2.
