### ISSUE TITLE
Issue building this projectv- missing artifacts

### ISSUE THREAD

**Issue by MrMXBryant** [Acosix/alfresco-simple-content-stores#36]
While building this project, I receive the following error: 
[ERROR] Failed to execute goal de.acosix.maven:jshint-plugin:1.1.0:jshint (Validate Webapp) on project de.acosix.alfresco.simplecontentstores.repo: Execution Validate Webapp of goal de.acosix.maven:jshint-plugin:1.1.0:jshint failed: Plugin de.acosix.maven:jshint-plugin:1.1.0 or one of its dependencies could not be resolved: Could not find artifact de.acosix.alfresco.maven:de.acosix.alfresco.maven.definitions:jar:1.4.0-SNAPSHOT in ossrh (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

I have oss snapshot url in the pom.xml and it still cannot find the dependency.

**Comment by MrMXBryant** [comment]
corrected

**Comment by AFaust** [comment]
Ah - I remember now. THere was a bug in the 1.4.0 parent POM which referenced the 1.4.0-SNAPSHOT definitions, and I needed to do a 1.4.1 release to fix that. The 1.4.0-SNAPSHOT unfortunately was auto-removed after a certain amount of time by the OSS Snapshot Repository (they have that automated).

**Comment by MrMXBryant** [comment]
Axel, thanks for the response. I checked OSS and made the necessary pom version updates. Also, I was able to get the encrypted file store working. Thank you so much for developing this.
