### ISSUE TITLE
Encryption not working: Key marked as blocked

### ISSUE THREAD

**Issue by thijslemmens** [Acosix/alfresco-simple-content-stores#39]
I'm using an Alfresco 7.2 and the current master for testing out encryption and key rotation, When I only add one key to a fresh install, it seems to get blocked every time:
`[ALFRESCO] 2022-08-24 15:02:40,700  WARN  [store.encrypted.MasterKeyManagerImpl] [main] More encryption master keys were configured / made available than on other servers in the same cluster - the following keys will be marked as blocked: [master:encryption]`

I attached a debugger, and the MasterKeyManagerImpl.getExtraneousKeys seems to be returning the key I added because the masterKeyCheckDataCache is empty.

**Comment by thijslemmens** [comment]
This is my configuration:
```
simpleContentStores=true
simpleContentStores.customStores=myEncryptingStore,defaultTenantFileContentStore
simpleContentStores.rootStore=myEncryptingStore
simpleContentStores.encryption.keystoreIds=master
simpleContentStores.encryption.keystore.master.location=file:/encryptionstore
simpleContentStores.encryption.keystore.master.password=helloworld
simpleContentStores.encryption.keystore.master.aliases=encryption
simpleContentStores.encryption.keystore.master.encryption.password=helloworld
simpleContentStores.encryption.keystore.master.type=JKS
simpleContentStores.customStore.myEncryptingStore.type=encryptingFacadeStore
simpleContentStores.customStore.myEncryptingStore.ref.backingStore=defaultTenantFileContentStore
```

**Comment by thijslemmens** [comment]
I think the WARN I'm getting is to be expected, but I must be missing some configuration to enable the encryption itself.

**Comment by thijslemmens** [comment]
Something that is in the title, but not really in the description:

- Alfresco does start with this config
- When uploading a file in Share, it works
- When accessing the file on disk, I can open it and read it

So this configuration does not seam to enable encryption.

**Comment by AFaust** [comment]
@thijslemmens I did not notice it at first, but I see your first property is defined as `simpleContentStores=true` - this should be `simpleContentStores.enabled=true`. I hope this is only a matter of an incomplete copy from your config to this issue, and not the (trivial) root cause of your troubles. I will check on my end nonetheless.

**Comment by AFaust** [comment]
The WARN message about extraneous keys can indeed be a false-positive message as it results from a check of locally configured master keys against cluster defined keys. For the first / only instance in an Alfresco environment, the validation check occurs before the instance has stored its master keys as the set of available master keys within the cluster via the cache, so all its keys are determined to be extraneous. This is a simple error in validation vs. initialisation.

**Comment by thijslemmens** [comment]
> @thijslemmens I did not notice it at first, but I see your first property is defined as `simpleContentStores=true` - this should be `simpleContentStores.enabled=true`. I hope this is only a matter of an incomplete copy from your config to this issue, and not the (trivial) root cause of your troubles. I will check on my end nonetheless.

Oh boy. You are right. I was thinking it was all configured because I see:
`
2022-08-31 06:35:28,036  INFO  [repo.beans.SimpleContentStoresBeanDefinitionEmitter] [main] Setting myEncryptingStore as root content store
`

I'll test again.
